# Generated by Django 5.1.2 on 2024-10-21 16:15

import apps.common.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAttendeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('organization_role', models.CharField(blank=True, max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_attendee_types', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Custom Attendee Type',
                'verbose_name_plural': 'Custom Attendee Types',
            },
        ),
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('organization_role', models.CharField(blank=True, max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitators', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Facilitator',
                'verbose_name_plural': 'Facilitators',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('attendee_type', models.CharField(choices=[('participant', 'Participant'), ('facilitator', 'Facilitator'), ('other', 'Other')], default='participant', max_length=20)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('attendance_status', models.CharField(choices=[('attended', 'Attended'), ('absent', 'Absent')], default='attended', max_length=20)),
                ('custom_attendee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_attendees', to='attendees.customattendeetype')),
                ('event', models.ForeignKey(default=apps.common.utils.get_default_event, on_delete=django.db.models.deletion.PROTECT, related_name='event_attendees', to='events.event')),
                ('organizations', models.ManyToManyField(related_name='event_attendees', to='organizations.organization')),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_attendees', to='attendees.facilitator')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_attendees', to='attendees.participant')),
            ],
            options={
                'verbose_name': 'Event Attendee',
                'verbose_name_plural': 'Event Attendees',
                'unique_together': {('event', 'custom_attendee_type', 'facilitator'), ('event', 'custom_attendee_type', 'participant'), ('event', 'facilitator'), ('event', 'participant')},
            },
        ),
    ]
