# Generated by Django 5.1.1 on 2024-10-07 11:51

import django.db.models.deletion
import obwob.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obwob', '0002_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='event',
            field=models.ForeignKey(default=obwob.models.get_default_event, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='obwob.event'),
        ),
    ]
