# Generated by Django 5.1.1 on 2024-10-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obwob', '0005_organization_organizationcoordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationcoordinator',
            name='organization',
        ),
        migrations.AddField(
            model_name='organizationcoordinator',
            name='organization',
            field=models.ManyToManyField(related_name='coordinators', to='obwob.organization'),
        ),
    ]
