# Generated by Django 5.1.1 on 2024-10-08 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obwob', '0006_remove_organizationcoordinator_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='events', to='obwob.organization'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilitators', to='obwob.organization'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='organization_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='obwob.organization'),
        ),
        migrations.RemoveField(
            model_name='organizationcoordinator',
            name='organization',
        ),
        migrations.AddField(
            model_name='organizationcoordinator',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='obwob.organization'),
        ),
    ]
