# Generated by Django 5.1.1 on 2024-10-14 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obwob', '0008_alter_participant_participant_identifier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='facilitator',
            options={'verbose_name': 'Facilitator', 'verbose_name_plural': 'Facilitators'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='organizationcoordinator',
            options={'verbose_name': 'Organization Coordinator', 'verbose_name_plural': 'Organization Coordinators'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': 'Response', 'verbose_name_plural': 'Responses'},
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='participant_identifier',
            new_name='unique_id',
        ),
        migrations.AddField(
            model_name='participant',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='organizationcoordinator',
            name='organization_role',
            field=models.CharField(default='OBWOB Coordinator', max_length=100),
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to='obwob.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_events', to='obwob.participant')),
            ],
            options={
                'verbose_name': 'Event Participant',
                'verbose_name_plural': 'Event Participants',
            },
        ),
        migrations.DeleteModel(
            name='ParticipantEvent',
        ),
    ]
