# Generated by Django 5.1.2 on 2024-10-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendees', '0001_initial'),
        ('events', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('choice', 'Choice')], max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographic_categories', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Demographic Category',
                'verbose_name_plural': 'Demographic Categories',
            },
        ),
        migrations.CreateModel(
            name='EventDemographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_demographics', to='demographics.demographiccategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_demographics', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Demographic',
                'verbose_name_plural': 'Event Demographics',
            },
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.CharField(max_length=255)),
                ('event_attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='attendees.eventattendee')),
                ('event_demographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='demographics.eventdemographic')),
            ],
            options={
                'verbose_name': 'Demographic',
                'verbose_name_plural': 'Demographics',
            },
        ),
    ]
